#!/usr/bin/env bash

# Marriage events
echo "accou_marriage.0001 event option a: $(grep -a "accou_marriage.0001 event option a" debug.log | wc -l)"
echo "- success: $(grep -a "accou_marriage.0001 event option a success" debug.log | wc -l)"
echo "- failure: $(grep -a "accou_marriage.0001 event option a failure" debug.log | wc -l)"
echo "- failure fp: $(pcre2grep -a "accou_marriage.0001 event option a failure, courtier: .+ \([\d]+\), candidate: .+ \([\d]+\), matchmaker: .+ \([\d]+\)" debug.log | wc -l)"
echo
echo "accou_marriage.0002 event option a: $(grep -a "accou_marriage.0002 event option a" debug.log | wc -l)"
echo "- outsider: $(grep -a "accou_marriage.0002 event option a, .*, outsider: yes" debug.log | wc -l)"
echo "- insider: $(grep -a "accou_marriage.0002 event option a, .*, outsider: no" debug.log | wc -l)"
echo "accou_marriage.0002 event option b: $(grep -a "accou_marriage.0002 event option b" debug.log | wc -l)"
echo "- outsider: $(grep -a "accou_marriage.0002 event option b, .*, outsider: yes" debug.log | wc -l)"
echo "- insider: $(grep -a "accou_marriage.0002 event option b, .*, outsider: no" debug.log | wc -l)"
pcre2grep -a -o1 "candidate quality: ([\d]+)" debug.log | awk '{s+=$1}END{print "average candidate quality:",s/NR}' RS="\n"
echo
echo "accou_courtier.0001 event option a: $(grep -a "accou_courtier.0001 event option a" debug.log | wc -l)"
echo "- success: $(grep -a "accou_courtier.0001 event option a success" debug.log | wc -l)"
echo "- failure: $(grep -a "accou_courtier.0001 event option a failure" debug.log | wc -l)"
echo
echo "accou_courtier.0002 event option a: $(grep -a "accou_courtier.0002 event option a" debug.log | wc -l)"
echo "- success: $(grep -a "accou_courtier.0002 event option a success" debug.log | wc -l)"
echo "- failure: $(grep -a "accou_courtier.0002 event option a failure" debug.log | wc -l)"
echo
echo "accou_courtier.0003 event option a: $(grep -a "accou_courtier.0003 event option a" debug.log | wc -l)"
echo "---"
echo "- chancellor: $(grep -a "accou_courtier.0003 event option a, .*, position: Chancellor" debug.log | wc -l)"
echo "- marshal: $(grep -a "accou_courtier.0003 event option a, .*, position: Marshal" debug.log | wc -l)"
echo "- steward: $(grep -a "accou_courtier.0003 event option a, .*, position: Steward" debug.log | wc -l)"
echo "- spymaster: $(grep -a "accou_courtier.0003 event option a, .*, position: Spymaster" debug.log | wc -l)"
echo "- court_chaplain: $(grep -a "accou_courtier.0003 event option a, .*, position: court_chaplain" debug.log | wc -l)"
echo "- personal_steward: $(grep -a "accou_courtier.0003 event option a, .*, position: personal_steward" debug.log | wc -l)"
echo "- admiral: $(grep -a "accou_courtier.0003 event option a, .*, position: Admiral" debug.log | wc -l)"
echo "- castellan: $(grep -a "accou_courtier.0003 event option a, .*, position: Castellan" debug.log | wc -l)"
echo "- kingsguard: $(grep -a "accou_courtier.0003 event option a, .*, position: kingsguard" debug.log | wc -l)"
echo "---"
echo "- court_physician: $(grep -a "accou_courtier.0003 event option a, .*, position: .*court_physician" debug.log | wc -l)"
echo "- cultural_emissary: $(grep -a "accou_courtier.0003 event option a, .*, position: cultural_emissary" debug.log | wc -l)"
echo "- keeper_of_swans: $(grep -a "accou_courtier.0003 event option a, .*, position: keeper_of_swans" debug.log | wc -l)"
echo "- court_gardener: $(grep -a "accou_courtier.0003 event option a, .*, position: court_gardener" debug.log | wc -l)"
echo "- lady_in_waiting: $(grep -a "accou_courtier.0003 event option a, .*, position: lady_in_waiting" debug.log | wc -l)"
echo "- antiquarian: $(grep -a "accou_courtier.0003 event option a, .*, position: antiquarian" debug.log | wc -l)"
echo "- travel_leader: $(grep -a "accou_courtier.0003 event option a, .*, position: travel_leader" debug.log | wc -l)"
echo "- wet_nurse: $(grep -a "accou_courtier.0003 event option a, .*, position: wet_nurse" debug.log | wc -l)"
echo "- court_tutor: $(grep -a "accou_courtier.0003 event option a, .*, position: court_tutor" debug.log | wc -l)"
echo "- food_taster: $(grep -a "accou_courtier.0003 event option a, .*, position: food_taster" debug.log | wc -l)"
echo "- master_of_horse: $(grep -a "accou_courtier.0003 event option a, .*, position: master_of_horse" debug.log | wc -l)"
echo "- master_of_hunt: $(grep -a "accou_courtier.0003 event option a, .*, position: master_of_hunt" debug.log | wc -l)"
echo "- royal_architect: $(grep -a "accou_courtier.0003 event option a, .*, position: royal_architect" debug.log | wc -l)"
echo "- seneschal: $(grep -a "accou_courtier.0003 event option a, .*, position: seneschal" debug.log | wc -l)"
echo "- cupbearer: $(grep -a "accou_courtier.0003 event option a, .*, position: cupbearer" debug.log | wc -l)"
echo "- chief_eunuch: $(grep -a "accou_courtier.0003 event option a, .*, position: chief_eunuch" debug.log | wc -l)"
echo "- court_jester: $(grep -a "accou_courtier.0003 event option a, .*, position: court_jester" debug.log | wc -l)"
echo "- court_poet: $(grep -a "accou_courtier.0003 event option a, .*, position: court_poet" debug.log | wc -l)"
echo "- court_musician: $(grep -a "accou_courtier.0003 event option a, .*, position: court_musician" debug.log | wc -l)"
echo "- bodyguard: $(grep -a "accou_courtier.0003 event option a, .*, position: bodyguard" debug.log | wc -l)"
echo "- champion: $(grep -a "accou_courtier.0003 event option a, .*, position: champion" debug.log | wc -l)"
echo "- executioner: $(grep -a "accou_courtier.0003 event option a, .*, position: executioner" debug.log | wc -l)"
echo "- court_artificer: $(grep -a "accou_courtier.0003 event option a, .*, position: court_artificer" debug.log | wc -l)"
echo "- court_cave_hermit: $(grep -a "accou_courtier.0003 event option a, .*, position: court_cave_hermit" debug.log | wc -l)"
echo "- master_assassin: $(grep -a "accou_courtier.0003 event option a, .*, position: master_assassin" debug.log | wc -l)"
echo "- court_scholar: $(grep -a "accou_courtier.0003 event option a, .*, position: court_scholar" debug.log | wc -l)"
echo "- maester: $(grep -a "accou_courtier.0003 event option a, .*, position: maester" debug.log | wc -l)"
echo "- household_guard: $(grep -a "accou_courtier.0003 event option a, .*, position: household_guard" debug.log | wc -l)"
echo "- septon: $(grep -a "accou_courtier.0003 event option a, .*, position: septon" debug.log | wc -l)"
echo "- septa: $(grep -a "accou_courtier.0003 event option a, .*, position: septa" debug.log | wc -l)"
echo "- gaoler: $(grep -a "accou_courtier.0003 event option a, .*, position: gaoler" debug.log | wc -l)"
echo "- harbormaster: $(grep -a "accou_courtier.0003 event option a, .*, position: harbormaster" debug.log | wc -l)"
echo "- master_at_arms: $(grep -a "accou_courtier.0003 event option a, .*, position: master_at_arms" debug.log | wc -l)"
echo "- court_smith: $(grep -a "accou_courtier.0003 event option a, .*, position: court_smith" debug.log | wc -l)"
echo "---"
echo "accou_courtier.0003 event option b: $(grep -a "accou_courtier.0003 event option b" debug.log | wc -l)"
echo
